version: 2

sources:
  - name: erp adventure works
    description: Fonte AW
    schema: AW_ERP_RAW

    tables:
      - name: production_product
        columns: 
            - name: productid
              tests: 
                - unique
                - not_null
          
      - name: production_productcategory
        columns: 
            - name: productcategoryid
              tests: 
                - unique
                - not_null
      - name: production_productsubcategory
        columns: 
            - name: productsubcategoryid
              tests: 
                - unique
                - not_null
<<<<<<< HEAD

      - name: person_countryregion
        columns: 
            - name: countryregioncode
              tests: 
                - unique
                - not_null

      - name: person_stateprovince
        columns: 
            - name: stateprovinceid
              tests: 
                - unique
                - not_null
      - name: person_address
        columns: 
            - name: addressid
              tests: 
                - unique
                - not_null
=======
>>>>>>> d2c549dc997b03c7cac6c39bdf2990f7020e4aee
      - name: sales_salesorderheader
        description: Uma linha por pedido
        columns:
          - name: salesorderid
            tests:
              - unique
              - not_null
<<<<<<< HEAD


=======
              
      - name: sales_salesorderheadersalesreason
        description:  id motivo de venda x id pedido
        columns:
          - name: salesorderid
            tests:
              - unique
              - not_null
      - name: sales_salesreason
        description: motivo de venda
        columns:
          - name: salesreasonid
            tests:
              - unique
              - not_null

      - name: sales_creditcard
        description: tipo de cartao de credito
        columns:
          - name: creditcardid
            tests:
              - unique
              - not_null
      - name: sales_salesorderdetail
      - name: sales_specialoffer
        description: tipo de oferta
        columns:
          - name: specialofferid
            tests:
              - unique
              - not_null

      
      
>>>>>>> d2c549dc997b03c7cac6c39bdf2990f7020e4aee
