version: 2

sources:
  - name: erp adventure works
    description: Fonte AW
    schema: AW_ERP_RAW

    tables:
      - name: production_product
        columns: 
            - name: productid
              tests: 
                - unique
                - not_null
          
      - name: production_productcategory
        columns: 
            - name: productcategoryid
              tests: 
                - unique
                - not_null
      - name: production_productsubcategory
        columns: 
            - name: productsubcategoryid
              tests: 
                - unique
                - not_null

      - name: person_countryregion
        columns: 
            - name: countryregioncode
              tests: 
                - unique
                - not_null

      - name: person_stateprovince
        columns: 
            - name: stateprovinceid
              tests: 
                - unique
                - not_null
      - name: person_address
        columns: 
            - name: addressid
              tests: 
                - unique
                - not_null

      - name: sales_salesorderheader
        description: Uma linha por pedido
        columns:
          - name: salesorderid
            tests:
              - unique
              - not_null
          
      - name: sales_salesorderheadersalesreason
        description:  id motivo de venda x id pedido
        columns:
          - name: salesorderid
            tests:
              - not_null
      - name: sales_salesreason
        description: motivo de venda
        columns:
          - name: salesreasonid
            tests:
              - unique
              - not_null

      - name: sales_creditcard
        description: tipo de cartao de credito
        columns:
          - name: creditcardid
            tests:
              - unique
              - not_null
      
      - name: sales_salesorderdetail
        description: detalhe do pedido
        columns:
          - name: salesorderdetailid
            tests:
              - unique
              - not_null
     
      - name: sales_specialoffer
        description: tipo de oferta
        columns:
          - name: specialofferid
            tests:
              - unique
              - not_null

      - name: sales_customer
        columns:
          - name: customerid
            tests:
              - unique
              - not_null

      - name: person_person
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null

      - name: person_businessentityaddress
        columns:
          - name: businessentityid
            tests:
              - not_null


         